version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: storicardchallenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mi_red
  storicard_service:
    build: .
    ports:
      - "8080:8080"  # Ejemplo de mapeo de puertos
    networks:
      - mi_red
    environment:
      POSTGRES_DB: storicardchallenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: "5432"

volumes:
  pg_data:

networks:
  mi_red:
    driver: bridge
